/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author darwi
 */
public class ventana_principal extends javax.swing.JFrame {

    /**
     * Creates new form ventana_pricipal
     */
    public ventana_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_crear = new javax.swing.JMenu();
        menuitem_usuarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuitem_labs = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuitem_solicitudes = new javax.swing.JMenuItem();
        menu_reservar = new javax.swing.JMenu();
        menuitem_labs1 = new javax.swing.JMenuItem();
        menu_ver = new javax.swing.JMenu();
        menuitem_Hlabs = new javax.swing.JMenuItem();
        menu_reportes = new javax.swing.JMenu();
        menuitem_labmasreservado = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuitem_totallabsreservados = new javax.swing.JMenuItem();
        menu_acercade = new javax.swing.JMenu();
        menuitem_acercade = new javax.swing.JMenuItem();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/campus2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(855, 522));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/flecha-izquierda.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/campus2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_regresar)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setToolTipText("");

        menu_crear.setText("Crear");
        menu_crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuitem_usuarios.setText("Usuarios");
        menuitem_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_usuariosActionPerformed(evt);
            }
        });
        menu_crear.add(menuitem_usuarios);
        menu_crear.add(jSeparator2);

        menuitem_labs.setText("Laboratorios");
        menu_crear.add(menuitem_labs);
        menu_crear.add(jSeparator4);

        menuitem_solicitudes.setText("Solicitudes");
        menu_crear.add(menuitem_solicitudes);

        jMenuBar1.add(menu_crear);

        menu_reservar.setText("Reservar");
        menu_reservar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuitem_labs1.setText("Laboratorios");
        menu_reservar.add(menuitem_labs1);

        jMenuBar1.add(menu_reservar);

        menu_ver.setText("Ver Laboratorios");
        menu_ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuitem_Hlabs.setText("Laboratorios");
        menuitem_Hlabs.setActionCommand("Horario Laboratorios");
        menu_ver.add(menuitem_Hlabs);

        jMenuBar1.add(menu_ver);

        menu_reportes.setText("Reportes");
        menu_reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuitem_labmasreservado.setText("Laboratorio mas reservado");
        menu_reportes.add(menuitem_labmasreservado);
        menu_reportes.add(jSeparator1);

        menuitem_totallabsreservados.setText("Total Laboratorios reservados");
        menu_reportes.add(menuitem_totallabsreservados);

        jMenuBar1.add(menu_reportes);

        menu_acercade.setText("Acerca de");
        menu_acercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuitem_acercade.setText("Informacion");
        menu_acercade.add(menuitem_acercade);

        jMenuBar1.add(menu_acercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuitem_usuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista.ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    public javax.swing.JMenu menu_acercade;
    public javax.swing.JMenu menu_crear;
    public javax.swing.JMenu menu_reportes;
    public javax.swing.JMenu menu_reservar;
    public javax.swing.JMenu menu_ver;
    public javax.swing.JMenuItem menuitem_Hlabs;
    public javax.swing.JMenuItem menuitem_acercade;
    public javax.swing.JMenuItem menuitem_labmasreservado;
    public javax.swing.JMenuItem menuitem_labs;
    public javax.swing.JMenuItem menuitem_labs1;
    public javax.swing.JMenuItem menuitem_solicitudes;
    public javax.swing.JMenuItem menuitem_totallabsreservados;
    public javax.swing.JMenuItem menuitem_usuarios;
    // End of variables declaration//GEN-END:variables
}
